### ISSUE TITLE
Slow Z doesn't affect stated print time

### ISSUE THREAD

**Issue by JustinMorgan** [5axes/Cura-Slow-Z#1]
Changing the Slow Z settings doesn't seem to affect Cura's print time estimate. It still says 9 hours and 30 minutes when I change the settings or disable Slow Z. I haven't timed the actual print yet. Pics:

![Capture 1](https://github.com/5axes/Cura-Slow-Z/assets/1706201/55581143-2f67-4c65-a082-19ccb6ee38cd)

![Capture 2](https://github.com/5axes/Cura-Slow-Z/assets/1706201/06317222-1f5d-48b0-94a3-76105697f3c7)

![Capture 3](https://github.com/5axes/Cura-Slow-Z/assets/1706201/aea29781-b662-4f7e-90ed-255daad2c506)

**Comment by 5axes** [comment]
That's normal; the plugin as every plugin of this type modify the final G-Code and not the result in Cura. So you can't see any difference.
